export function isMiningQuestion(question: string): boolean {
  const q = String(question).toLowerCase().trim();

  const miningTopics = [
    // Core mining
    "mining",
    "mine",
    "mines",
    "miner",
    "miners",
    "mineral",
    "minerals",
    "ore",
    "ores",
    "orebody",
    "ore body",
    "deposit",
    "deposits",
    "mineral deposit",
    "mineral deposits",

    // Commodities
    "gold",
    "silver",
    "copper",
    "lithium",
    "bronze",
    "brass",
    "alloy",
    "smelting",
    "metallurgy",
    "coal",
    "nickel",
    "cobalt",
    "uranium",
    "zinc",
    "lead",
    "tin",
    "platinum",
    "palladium",
    "bauxite",
    "aluminium",
    "aluminum",
    "iron ore",
    "iron",
    "rare earth",
    "rare earths",
    "graphite",
    "manganese",
    "potash",

    // Exploration / geology
    "exploration",
    "mineral exploration",
    "exploration project",
    "exploration drilling",
    "drilling",
    "drill hole",
    "drill holes",
    "geology",
    "geological",
    "geologist",
    "geologists",
    "geochemistry",
    "geophysics",
    "resource estimation",
    "mineral resource",
    "mineral resources",
    "mineral reserve",
    "mineral reserves",

    // Mining methods
    "open pit",
    "open-pit",
    "open cut",
    "open-cut",
    "underground mining",
    "underground mine",
    "underground mines",
    "surface mining",
    "strip mining",
    "placer mining",
    "hard rock mining",
    "room and pillar",
    "longwall mining",
    "block caving",
    "sublevel caving",
    "cut and fill",
    "shrinkage stoping",
    "stoping",

    // Processing
    "ore processing",
    "mineral processing",
    "mineral beneficiation",
    "beneficiation",
    "crushing",
    "grinding",
    "flotation",
    "leaching",
    "smelting",
    "refining",
    "concentrate",
    "concentrator",
    "heap leaching",
    "cyanidation",
    "separation",

    // Operations
    "mine production",
    "mineral production",
    "ore production",
    "mine operation",
    "mine operations",
    "mining operation",
    "mining operations",
    "mine development",
    "mine construction",
    "mine planning",
    "mine plan",
    "production mining",

    // Equipment
    "mining equipment",
    "mining machinery",
    "mining machine",
    "haul truck",
    "haul trucks",
    "excavator",
    "excavators",
    "drill rig",
    "drill rigs",
    "dragline",
    "crusher",
    "conveyor",
    "mining technology",
    "loader",
    "dozer",
    "bulldozer",
    "shovel",

    // Safety
    "mine safety",
    "mining safety",
    "mine accident",
    "mining accident",
    "mine hazard",
    "mining hazard",
    "mine ventilation",
    "mining ventilation",
    "mine rescue",
    "mine emergency",
    "mining emergency",
    "ground control",
    "ground stability",
    "roof control",
    "roof fall",
    "mine fire",
    "explosion",
    "coal dust",
    "respirable dust",
    "silica dust",
    "silica exposure",
    "occupational safety",
    "occupational health",

    // Regulations
    "msha",
    "mining regulation",
    "mining regulations",
    "mine regulation",
    "mine regulations",
    "mining law",
    "mining laws",
    "mining permit",
    "mining permits",
    "mining licence",
    "mining license",
    "mineral rights",
    "environmental permit",
    "environmental permits",
    "regulatory compliance",
    "mining compliance",

    // Environment
    "mining environment",
    "environmental impact",
    "environmental impacts",
    "mine rehabilitation",
    "mine reclamation",
    "mining waste",
    "tailings",
    "mine water",
    "acid mine drainage",
    "mine closure",
    "mine closure plan",
    "environmental management",

    // Industry
    "mining company",
    "mining companies",
    "mining project",
    "mining projects",
    "mining industry",
    "mining sector",
    "mineral industry",
    "mining investment",
    "mining economics",
    "mining market",
    "mining business",
    "mining stocks",
    "mining shares",

    // Mining Discovery
    "mining discovery",
    "mining discovery website",
    "mining discovery services",

    // Company / industry updates
    "press release",
    "press releases",
    "company announcement",
    "company announcements",
    "exchange release",
    "regulatory filing",
    "regulatory filings",
    "sec filing",
    "sec filings",
  ];

  return miningTopics.some((topic) => q.includes(topic));
}